/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { VerificationToken } from "./VerificationToken";
import { VerificationTokenCountArgs } from "./VerificationTokenCountArgs";
import { VerificationTokenFindManyArgs } from "./VerificationTokenFindManyArgs";
import { VerificationTokenFindUniqueArgs } from "./VerificationTokenFindUniqueArgs";
import { CreateVerificationTokenArgs } from "./CreateVerificationTokenArgs";
import { UpdateVerificationTokenArgs } from "./UpdateVerificationTokenArgs";
import { DeleteVerificationTokenArgs } from "./DeleteVerificationTokenArgs";
import { User } from "../../user/base/User";
import { VerificationTokenService } from "../verificationToken.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => VerificationToken)
export class VerificationTokenResolverBase {
  constructor(
    protected readonly service: VerificationTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "any",
  })
  async _verificationTokensMeta(
    @graphql.Args() args: VerificationTokenCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [VerificationToken])
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "any",
  })
  async verificationTokens(
    @graphql.Args() args: VerificationTokenFindManyArgs
  ): Promise<VerificationToken[]> {
    return this.service.verificationTokens(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => VerificationToken, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "own",
  })
  async verificationToken(
    @graphql.Args() args: VerificationTokenFindUniqueArgs
  ): Promise<VerificationToken | null> {
    const result = await this.service.verificationToken(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VerificationToken)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "create",
    possession: "any",
  })
  async createVerificationToken(
    @graphql.Args() args: CreateVerificationTokenArgs
  ): Promise<VerificationToken> {
    return await this.service.createVerificationToken({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VerificationToken)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "update",
    possession: "any",
  })
  async updateVerificationToken(
    @graphql.Args() args: UpdateVerificationTokenArgs
  ): Promise<VerificationToken | null> {
    try {
      return await this.service.updateVerificationToken({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VerificationToken)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "delete",
    possession: "any",
  })
  async deleteVerificationToken(
    @graphql.Args() args: DeleteVerificationTokenArgs
  ): Promise<VerificationToken | null> {
    try {
      return await this.service.deleteVerificationToken(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: VerificationToken
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
