/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VerificationTokenService } from "../verificationToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VerificationTokenCreateInput } from "./VerificationTokenCreateInput";
import { VerificationToken } from "./VerificationToken";
import { VerificationTokenFindManyArgs } from "./VerificationTokenFindManyArgs";
import { VerificationTokenWhereUniqueInput } from "./VerificationTokenWhereUniqueInput";
import { VerificationTokenUpdateInput } from "./VerificationTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VerificationTokenControllerBase {
  constructor(
    protected readonly service: VerificationTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VerificationToken })
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVerificationToken(
    @common.Body() data: VerificationTokenCreateInput
  ): Promise<VerificationToken> {
    return await this.service.createVerificationToken({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,
        token: true,
        expires: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VerificationToken] })
  @ApiNestedQuery(VerificationTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async verificationTokens(
    @common.Req() request: Request
  ): Promise<VerificationToken[]> {
    const args = plainToClass(VerificationTokenFindManyArgs, request.query);
    return this.service.verificationTokens({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,
        token: true,
        expires: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VerificationToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async verificationToken(
    @common.Param() params: VerificationTokenWhereUniqueInput
  ): Promise<VerificationToken | null> {
    const result = await this.service.verificationToken({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,
        token: true,
        expires: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VerificationToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVerificationToken(
    @common.Param() params: VerificationTokenWhereUniqueInput,
    @common.Body() data: VerificationTokenUpdateInput
  ): Promise<VerificationToken | null> {
    try {
      return await this.service.updateVerificationToken({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          identifier: true,
          token: true,
          expires: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VerificationToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVerificationToken(
    @common.Param() params: VerificationTokenWhereUniqueInput
  ): Promise<VerificationToken | null> {
    try {
      return await this.service.deleteVerificationToken({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          identifier: true,
          token: true,
          expires: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
