/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { VerificationTokenUpdateManyWithoutUsersInput } from "./VerificationTokenUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { CarUpdateManyWithoutUsersInput } from "./CarUpdateManyWithoutUsersInput";
import { QueueUpdateManyWithoutUsersInput } from "./QueueUpdateManyWithoutUsersInput";
import { SessionUpdateManyWithoutUsersInput } from "./SessionUpdateManyWithoutUsersInput";
import { AccountUpdateManyWithoutUsersInput } from "./AccountUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => VerificationTokenUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VerificationTokenUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VerificationTokenUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  verificationTokens?: VerificationTokenUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CarUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CarUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CarUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  cars?: CarUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => QueueUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => QueueUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => QueueUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  queues?: QueueUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SessionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SessionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  sessions?: SessionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AccountUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AccountUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AccountUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  accounts?: AccountUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
