/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { VerificationTokenCreateNestedManyWithoutUsersInput } from "./VerificationTokenCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { CarCreateNestedManyWithoutUsersInput } from "./CarCreateNestedManyWithoutUsersInput";
import { QueueCreateNestedManyWithoutUsersInput } from "./QueueCreateNestedManyWithoutUsersInput";
import { SessionCreateNestedManyWithoutUsersInput } from "./SessionCreateNestedManyWithoutUsersInput";
import { AccountCreateNestedManyWithoutUsersInput } from "./AccountCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => VerificationTokenCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VerificationTokenCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VerificationTokenCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  verificationTokens?: VerificationTokenCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CarCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CarCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CarCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  cars?: CarCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => QueueCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => QueueCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => QueueCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  queues?: QueueCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SessionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SessionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  sessions?: SessionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AccountCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AccountCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AccountCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  accounts?: AccountCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
