/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CarBrand } from "./CarBrand";
import { CarBrandCountArgs } from "./CarBrandCountArgs";
import { CarBrandFindManyArgs } from "./CarBrandFindManyArgs";
import { CarBrandFindUniqueArgs } from "./CarBrandFindUniqueArgs";
import { CreateCarBrandArgs } from "./CreateCarBrandArgs";
import { UpdateCarBrandArgs } from "./UpdateCarBrandArgs";
import { DeleteCarBrandArgs } from "./DeleteCarBrandArgs";
import { CarFindManyArgs } from "../../car/base/CarFindManyArgs";
import { Car } from "../../car/base/Car";
import { CarBrandService } from "../carBrand.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CarBrand)
export class CarBrandResolverBase {
  constructor(
    protected readonly service: CarBrandService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "read",
    possession: "any",
  })
  async _carBrandsMeta(
    @graphql.Args() args: CarBrandCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CarBrand])
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "read",
    possession: "any",
  })
  async carBrands(
    @graphql.Args() args: CarBrandFindManyArgs
  ): Promise<CarBrand[]> {
    return this.service.carBrands(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CarBrand, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "read",
    possession: "own",
  })
  async carBrand(
    @graphql.Args() args: CarBrandFindUniqueArgs
  ): Promise<CarBrand | null> {
    const result = await this.service.carBrand(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CarBrand)
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "create",
    possession: "any",
  })
  async createCarBrand(
    @graphql.Args() args: CreateCarBrandArgs
  ): Promise<CarBrand> {
    return await this.service.createCarBrand({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CarBrand)
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "update",
    possession: "any",
  })
  async updateCarBrand(
    @graphql.Args() args: UpdateCarBrandArgs
  ): Promise<CarBrand | null> {
    try {
      return await this.service.updateCarBrand({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CarBrand)
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "delete",
    possession: "any",
  })
  async deleteCarBrand(
    @graphql.Args() args: DeleteCarBrandArgs
  ): Promise<CarBrand | null> {
    try {
      return await this.service.deleteCarBrand(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Car], { name: "cars" })
  @nestAccessControl.UseRoles({
    resource: "Car",
    action: "read",
    possession: "any",
  })
  async findCars(
    @graphql.Parent() parent: CarBrand,
    @graphql.Args() args: CarFindManyArgs
  ): Promise<Car[]> {
    const results = await this.service.findCars(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
