/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CarBrandService } from "../carBrand.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CarBrandCreateInput } from "./CarBrandCreateInput";
import { CarBrand } from "./CarBrand";
import { CarBrandFindManyArgs } from "./CarBrandFindManyArgs";
import { CarBrandWhereUniqueInput } from "./CarBrandWhereUniqueInput";
import { CarBrandUpdateInput } from "./CarBrandUpdateInput";
import { CarFindManyArgs } from "../../car/base/CarFindManyArgs";
import { Car } from "../../car/base/Car";
import { CarWhereUniqueInput } from "../../car/base/CarWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CarBrandControllerBase {
  constructor(
    protected readonly service: CarBrandService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CarBrand })
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCarBrand(
    @common.Body() data: CarBrandCreateInput
  ): Promise<CarBrand> {
    return await this.service.createCarBrand({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        brandName: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CarBrand] })
  @ApiNestedQuery(CarBrandFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async carBrands(@common.Req() request: Request): Promise<CarBrand[]> {
    const args = plainToClass(CarBrandFindManyArgs, request.query);
    return this.service.carBrands({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        brandName: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CarBrand })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async carBrand(
    @common.Param() params: CarBrandWhereUniqueInput
  ): Promise<CarBrand | null> {
    const result = await this.service.carBrand({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        brandName: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CarBrand })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCarBrand(
    @common.Param() params: CarBrandWhereUniqueInput,
    @common.Body() data: CarBrandUpdateInput
  ): Promise<CarBrand | null> {
    try {
      return await this.service.updateCarBrand({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          brandName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CarBrand })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCarBrand(
    @common.Param() params: CarBrandWhereUniqueInput
  ): Promise<CarBrand | null> {
    try {
      return await this.service.deleteCarBrand({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          brandName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/cars")
  @ApiNestedQuery(CarFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Car",
    action: "read",
    possession: "any",
  })
  async findCars(
    @common.Req() request: Request,
    @common.Param() params: CarBrandWhereUniqueInput
  ): Promise<Car[]> {
    const query = plainToClass(CarFindManyArgs, request.query);
    const results = await this.service.findCars(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        brandId: true,
        carTypeId: true,
        model: true,
        carNumber: true,

        user: {
          select: {
            id: true,
          },
        },

        carBrand: {
          select: {
            id: true,
          },
        },

        carType: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cars")
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "update",
    possession: "any",
  })
  async connectCars(
    @common.Param() params: CarBrandWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        connect: body,
      },
    };
    await this.service.updateCarBrand({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cars")
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "update",
    possession: "any",
  })
  async updateCars(
    @common.Param() params: CarBrandWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        set: body,
      },
    };
    await this.service.updateCarBrand({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cars")
  @nestAccessControl.UseRoles({
    resource: "CarBrand",
    action: "update",
    possession: "any",
  })
  async disconnectCars(
    @common.Param() params: CarBrandWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        disconnect: body,
      },
    };
    await this.service.updateCarBrand({
      where: params,
      data,
      select: { id: true },
    });
  }
}
